ekf_se_node:
  frequency: 30  # Fréquence de mise à jour
  sensor_timeout: 0.1  # Timeout des capteurs
  two_d_mode: true  # Si votre robot fonctionne en 2D

  odom0: odom
  odom0_config: [false, false, false,
                 true,  true,  true,
                 false, false, false,
                 false, false, false,
                 false, false, false]

  imu0: imu/data
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                true,  true,  true,
                false, false, false]

  imu0_differential: false
  imu0_relative: true
  imu0_remove_gravitational_acceleration: true

  use_control: false
  stamped_control: false

  publish_tf: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
